version: '3.1'
services:
  bookmedik:
    container_name: bookmedik
    image: javiutrera01/bookmedik:v2
    restart: always
    environment:
      DATABASE_NAME: bookmedik
      DATABASE_USER: bookmedik
      DATABASE_PASSWORD: bookmedik
      DATABASE_HOST: server_mariadb
    ports:
      - 8081:80
    depends_on:
      - db
  db:
    container_name: server_mariadb
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_DATABASE: bookmedik
      MYSQL_USER: bookmedik
      MYSQL_PASSWORD: bookmedik
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
    mariadb_data:

